# Generating Data with Numpy

### 1. Run these next few cells:

In [1]:
import numpy as np

In [2]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [3]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [4]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Generate 4 arrays of size 10:
    A) The first one should be "empty"
    B) The second one should be full of 0s
    C) The third one should be full of 1s
    D) The last one should be full of 2s
   (<b>Hint</b>: Try to use 4 different functions here.)

In [7]:
empty_arr = np.empty(10)
empty_arr

array([2.87663507e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [9]:
zeros_arr = np.zeros(10)
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
ones_arr = np.ones(10)
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
twos_arr = np.full(10,2)
twos_arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 3. Generate 4 more arrays. This time, they should be 2 by 4 arrays. 

In [14]:
empty_matrix = np.empty((2,4))
empty_matrix

array([[2.84072658e-316, 0.00000000e+000, 6.94092421e-310,
        6.94092421e-310],
       [6.94092421e-310, 6.94092421e-310, 6.94092421e-310,
        6.94092421e-310]])

In [15]:
zeros_matrix = np.zeros((2,4))
zeros_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
ones_matrix = np.ones((2,4))
ones_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
twos_matrix = np.full((2,4),2)
twos_matrix

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### 4. Use the <i> _like </i> functions to generate 4 more arrays:
    A) An empty array with the same shape as array_1D. 
    B) An 2-D array of 0s with the same shape as array_2D.
    C) A 3-D array of 1s with the same shappe as array_3D.
    D) A 3-D array of 2s with the same shape as array_3D. 

In [19]:
arr1 = np.empty_like(empty_arr)
arr1

array([1.e-323, 1.e-323, 1.e-323, 1.e-323, 1.e-323, 1.e-323, 1.e-323,
       1.e-323, 1.e-323, 1.e-323])

In [21]:
arr2 = np.zeros_like(zeros_arr)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
arr3 = np.ones_like(ones_arr)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
arr4 = np.full_like(twos_arr, 2)
arr4

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 5. With the help of the np.arange() function, generate several sequences of numbers:
    A) The integers from 0 to 50, excluding 50. 
    B) The integers from 1 to 50, including 50. 
    C) The integers from 25 to 50, including 50. 
    D) Every 5-th integers from 25 to 50, including 50. 
    E) Every 5-th integers from 25 to 50, including 50, represented as decimals of up to 32 bits. 

In [25]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [26]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
np.arange(25,51)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [28]:
np.arange(25,51, step = 5)

array([25, 30, 35, 40, 45, 50])

In [29]:
np.arange(25,51, step = 5, dtype = np.float32)

array([25., 30., 35., 40., 45., 50.], dtype=float32)

### 6. Import the following functions from the numpy.random module:
    A) Generator as "gen".
    B) PCG64 as "pcg"

In [30]:
from numpy.random import Generator as gen

In [31]:
from numpy.random import PCG64 as pcg

### 7. Create a random generator object.

In [34]:
random_obj = gen(pcg())

### 8. Using the .random() method, generate the following pseudo-random values:
    A) A single probability of an event occuring.
    B) An array of size 10 with the probabilities of 10 events. 
    C) A 5 by 10 2-D array with the probabilities of 50 events.  

In [37]:
random_obj.random()

0.8126506409229013

In [38]:
random_obj.random(10)

array([0.67435022, 0.51015024, 0.66684897, 0.81772014, 0.68975313,
       0.84899229, 0.92307939, 0.80148846, 0.68247393, 0.48499411])

In [40]:
random_obj.random((5,10))

array([[0.82162802, 0.64512923, 0.96403069, 0.12439309, 0.96878372,
        0.21253018, 0.36629825, 0.84764599, 0.18361311, 0.25677746],
       [0.97415336, 0.28286219, 0.36416364, 0.97918186, 0.73655754,
        0.61866025, 0.72141931, 0.67064127, 0.84238423, 0.96192632],
       [0.96841206, 0.69171471, 0.74803068, 0.22804591, 0.45721926,
        0.34433157, 0.25085468, 0.93102207, 0.16526401, 0.60577427],
       [0.93302117, 0.03407001, 0.50599382, 0.441425  , 0.22108284,
        0.92713773, 0.61404993, 0.30195361, 0.52185693, 0.10138198],
       [0.3615515 , 0.01398201, 0.01915321, 0.11283189, 0.97923019,
        0.71056485, 0.68977193, 0.79303653, 0.47736549, 0.66596958]])

### 9. Set the seed for the random generator to 123, and generate the same 3 sets of values:
    A) A single probability of an event occuring.
    B) An array of size 10 with the probabilities of 10 events. 
    C) A 5 by 10 2-D array with the probabilities of 50 events.  
   <b> Note: </b> The seed only lasts for a single method before it gets reset. Hence, make sure you define the seed before calling the method every time. 

In [44]:
arr = gen(pcg(seed = 123))
arr.random()

0.6823518632481435

In [45]:
arr = gen(pcg(123))
arr.random(10)

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

In [46]:
arr = gen(pcg(123))
arr.random((5,10))

array([[0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
        0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269],
       [0.51297046, 0.2449646 , 0.8242416 , 0.21376296, 0.74146705,
        0.6299402 , 0.92740726, 0.23190819, 0.79912513, 0.51816504],
       [0.23155562, 0.16590399, 0.49778897, 0.58272464, 0.18433799,
        0.01489492, 0.47113323, 0.72824333, 0.91860049, 0.62553401],
       [0.91712257, 0.86469025, 0.21814287, 0.86612743, 0.73075194,
        0.27786529, 0.79704355, 0.86522171, 0.2994379 , 0.52704208],
       [0.07148681, 0.58323841, 0.2379064 , 0.76496365, 0.17363164,
        0.31274226, 0.01447448, 0.03255192, 0.49670184, 0.46831253]])

### 10. Set the seed for the random generator to 123, and generate the following arrays of integers:
    A) A single integer between 0 and 10.
    B) A 1-D array of 10 integers between 0 and 100.
    C) A 5 by 10 array of two-digit integers.

In [48]:
arr = gen(pcg(123))
arr.integers(10)

0

In [50]:
arr = gen(pcg(123))
arr.integers(100, size = 10)

array([ 1, 68, 59,  5, 90, 22, 25, 18, 33, 17])

In [52]:
arr = gen(pcg(123))
arr.integers(10, size=(5,10))

array([[0, 6, 5, 0, 9, 2, 2, 1, 3, 1],
       [3, 8, 4, 9, 4, 2, 7, 8, 8, 8],
       [0, 5, 2, 2, 2, 8, 7, 2, 4, 7],
       [1, 6, 4, 9, 7, 2, 8, 7, 2, 5],
       [7, 2, 2, 1, 0, 4, 0, 5, 4, 1]])

### 11. For this next bit, check the NumPy documentation and select 3 different probability distributions (e.g. normal, poisson, binomial, logistic) and generate the following:
    A) One "default" value from one distribution (without specifying any non-mandatory arguments).
    B) An array of 10 values from the second distribution. 
    C) A 5 by 10 2-D array with values from the third distribution.

In [53]:
arr = gen(pcg(123))
arr.normal()

-0.9891213503478509

In [54]:
arr = gen(pcg(123))
arr.poisson(size = 10, lam = 15)

array([17, 11, 11, 22, 15, 19, 18, 22, 19, 12])

In [55]:
arr = gen(pcg(123))
arr.binomial(n = 100, p = 0.7, size = (5,10))

array([[67, 67, 72, 59, 77, 72, 81, 79, 67, 67],
       [62, 63, 72, 65, 77, 68, 73, 71, 69, 70],
       [72, 69, 72, 78, 70, 75, 61, 75, 72, 74],
       [75, 72, 70, 60, 77, 67, 70, 73, 67, 68],
       [59, 66, 65, 67, 76, 65, 68, 73, 66, 67]])