# Statistsics w/ NumPy

### 1. Run the following cells:

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 150, precision = 2)

In [3]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [4]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [5]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. For each of the 3 arrays we defined above, do the following:
    A) Call the np.max() or np.amax() function and plug in the array as an input. 
    B) Call the np.max() or np.amax() function along an axis of your choice and plug in the array as an input.
    C) Call the np.maximum.reduce() function and plug in the array as an input. 


In [6]:
np.max(array_1D)

14

In [7]:
np.max(array_2D)

87

In [9]:
np.max(array_3D)

54

In [12]:
np.max(array_1D, axis = 0)

14

In [14]:
np.max(array_2D, axis = 1)

array([60, 87, 55])

In [17]:
np.max(array_3D, axis = 2)

array([[ 5, 51],
       [15, 54]])

In [18]:
np.maximum.reduce(array_1D)

14

In [19]:
np.maximum.reduce(array_2D)

array([43, 54, 65, 76, 87])

In [20]:
np.maximum.reduce(array_3D)

array([[11, 12, 13, 14, 15],
       [51, 52, 53, 54, 51]])

### 3. For each array find the difference between its maximum and minimum. 
   <b>Note:</b> Use the <i>np.ptp() </i> function

In [21]:
np.ptp(array_1D)

4

In [22]:
np.ptp(array_2D)

76

In [23]:
np.ptp(array_3D)

53

### 4. For the 2-D and 3-D arrays find the difference between the maximum and minimum, for every row.

In [27]:
np.ptp(array_2D, axis = 1)

array([40, 44, 44])

In [29]:
np.ptp(array_3D, axis = 2)

array([[ 4, 40],
       [ 4, 49]])

### 5. For all 3 arrays we defined, use the<i> np.percentile() </i>and <i>np.quantile()</i> functions to find the following: 
    A) The 30-th percentile (or 0.3-th quantile). 
    B) The 66-th percentile (or 0.66-th qunatile). 
    C) The median. 
   (<b>Hint</b>: The median value is equivalent to the 50-th percentile)

#### 1D array:

In [30]:
np.sort(array_1D)

# We're also providing a sorted version of the inputs, so that the outputs are more easy to understand.

array([10, 11, 12, 13, 14])

In [31]:
np.percentile(array_1D, 30)

11.2

In [33]:
np.quantile(array_1D, 0.66)

12.64

In [34]:
np.median(array_1D)

12.0

#### 2D array:

In [35]:
np.sort(array_2D, axis = None)

# We're also providing a sorted version of the inputs, so that the outputs are more easy to understand.

array([11, 20, 22, 30, 33, 40, 43, 44, 50, 54, 55, 60, 65, 76, 87])

In [41]:
np.percentile(array_2D, 30)

34.4

In [42]:
np.quantile(array_2D, 0.66)

54.24

In [43]:
np.median(array_2D)

44.0

#### 3D array

In [44]:
np.sort(array_3D, axis = None)

# We're also providing a sorted version of the inputs, so that the outputs are more easy to understand.

array([ 1,  2,  3,  4,  5,  5, 11, 11, 12, 13, 14, 15, 21, 31, 41, 51, 51, 52, 53, 54])

In [45]:
np.percentile(array_3D, 30)

9.200000000000001

In [46]:
np.quantile(array_3D, 0.66)

26.40000000000001

In [47]:
np.quantile(array_3D, 0.5)

13.5

### 6. For the 3 arrays:
    A) Find the mean.
    B) Find the median.
    C) Find the mean along the columns.

#### 1D array:

In [48]:
np.mean(array_1D)

12.0

#### 2D array:

In [49]:
np.mean(array_2D)

46.0

#### 3D array:

In [51]:
np.mean(array_3D)

22.5

### 7. For the 2D array:
    A) Find the variance. 
    B) Find the standard deviation. 
    C) Find the covariance. 
    D) Find the correlation. 

In [53]:
np.var(array_2D)

416.6666666666667

In [54]:
np.std(array_2D)

20.412414523193153

In [55]:
np.cov(array_2D)

array([[250. , 275. , 275. ],
       [275. , 302.5, 302.5],
       [275. , 302.5, 302.5]])

In [56]:
np.corrcoef(array_2D)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 8. For the 2D array:
    A) Find the "default "bin edges for a histogram (don't specify any arguments)
    B) Set the number of bins to 6
    C) Define a range
    D) With the help of the matplotlib package, plot the 3 histograms

### 9. For the 3-D array:
    A) Take the first two rows, and compute their 2-D histogram, with 4 bins    .
    B) Take the entire 2-D array and find its 3-D histogram with 4 bins. 
   (<b>Hint</b>: You'll need to plug in the <b>transpose</b> for B to work) 
   

In [57]:
np.histogram2d(array_2D[0], array_2D[1], bins = 4)

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 2.]]),
 array([20., 30., 40., 50., 60.]),
 array([43., 54., 65., 76., 87.]))

In [59]:
np.histogramdd(array_2D.transpose(), bins = 4)

(array([[[1., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 2.]]]),
 [array([20., 30., 40., 50., 60.]),
  array([43., 54., 65., 76., 87.]),
  array([11., 22., 33., 44., 55.])])

### 10. Run the following cell, and then compute the following:
    A) The mean, using the np.mean() function.
    B) The mean, using the np.nanmean() function.
    C) The variance, using the np.var() function. 
    D) The variance, using the np.nanvar() funcion. 

In [60]:
array_nan = np.array([[20,np.nan,40,50,60], [np.nan,54,65,np.nan,87], [11,22,33,44,np.nan]])
array_nan

array([[20., nan, 40., 50., 60.],
       [nan, 54., 65., nan, 87.],
       [11., 22., 33., 44., nan]])

In [61]:
np.mean(array_nan)

nan

In [62]:
np.nanmean(array_nan)

44.18181818181818

In [63]:
np.var(array_nan)

nan

In [64]:
np.nanvar(array_nan)

451.6033057851239